{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Hotel Ratings",
    "description" : "Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization-262)** for more information on how to generate an access token. \n\nPlease also be aware that our test environment is based on a subset of the production, this API in test only offers 24 hotels; 10 in London and 14 in New-York. You can find the list in our **[data collection](https://github.com/amadeus4dev/data-collection)**.\n",
    "version" : "1.0.2"
  },
  "servers" : [ {
    "url" : "https://test.api.amadeus.com/v2"
  } ],
  "tags" : [ {
    "name" : "Hotel Ratings",
    "description" : "Sentiments about Hotels."
  } ],
  "paths" : {
    "/e-reputation/hotel-sentiments" : {
      "get" : {
        "tags" : [ "Hotel Ratings" ],
        "summary" : "Get sentiments by Amadeus Hotel Ids",
        "operationId" : "getSentimentsByHotelIds",
        "parameters" : [ {
          "name" : "hotelIds",
          "in" : "query",
          "description" : "Comma-separated list of Amadeus Hotel Ids (max. 3) . Amadeus Hotel Ids are found in the Hotel Search response (parameter name is 'hotelId').",
          "required" : true,
          "style" : "form",
          "explode" : false,
          "schema" : {
            "maxItems" : 100,
            "minItems" : 1,
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          },
          "example" : [ "TELONMFS" ]
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful operation",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "title" : "SuccessSentiments",
                  "type" : "object",
                  "example" : {
                    "data" : [ {
                      "hotelId" : "ADNYCCTB",
                      "numberOfRatings" : 278,
                      "numberOfReviews" : 218,
                      "overallRating" : 93,
                      "sentiments" : {
                        "catering" : 89,
                        "facilities" : 90,
                        "location" : 98,
                        "pointsOfInterest" : 91,
                        "roomComforts" : 92,
                        "service" : 98,
                        "sleepQuality" : 87,
                        "staff" : 100,
                        "valueForMoney" : 87
                      },
                      "type" : "hotelSentiment"
                    }, {
                      "hotelId" : "TELONMFS",
                      "numberOfRatings" : 2666,
                      "numberOfReviews" : 2667,
                      "overallRating" : 81,
                      "sentiments" : {
                        "catering" : 81,
                        "facilities" : 75,
                        "internet" : 72,
                        "location" : 89,
                        "pointsOfInterest" : 81,
                        "roomComforts" : 87,
                        "service" : 80,
                        "sleepQuality" : 78,
                        "staff" : 89,
                        "valueForMoney" : 75
                      },
                      "type" : "hotelSentiment"
                    } ],
                    "meta" : {
                      "count" : 1,
                      "links" : {
                        "self" : "https://test.api.amadeus.com/v2/e-reputation/hotel-sentiments?hotelIds=ADNYCCTB,TELONMFS,XXXYYY01"
                      }
                    },
                    "warnings" : [ {
                      "code" : 913,
                      "detail" : "Some of the requested properties were not found in our database.",
                      "source" : {
                        "parameter" : "hotelIds",
                        "pointer" : "XXXYYY01"
                      },
                      "title" : "PROPERTIES NOT FOUND"
                    } ]
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "Not Found",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error400"
                }
              }
            }
          },
          "401" : {
            "description" : "Unauthorized",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error401"
                }
              }
            }
          },
          "default" : {
            "description" : "Unexpected Error",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error500"
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "CollectionLinks" : {
        "title" : "CollectionLinks",
        "type" : "object",
        "properties" : {
          "first" : {
            "type" : "string",
            "format" : "uri",
            "example" : "https://test.api.amadeus.com/v1/area/resources?..."
          },
          "last" : {
            "type" : "string",
            "format" : "uri",
            "example" : "https://test.api.amadeus.com/v1/area/resources?..."
          },
          "next" : {
            "type" : "string",
            "format" : "uri",
            "example" : "https://test.api.amadeus.com/v1/area/resources?..."
          },
          "previous" : {
            "type" : "string",
            "format" : "uri",
            "example" : "https://test.api.amadeus.com/v1/area/resources?..."
          },
          "self" : {
            "type" : "string",
            "format" : "uri",
            "example" : "https://test.api.amadeus.com/v1/area/resources?..."
          },
          "up" : {
            "type" : "string",
            "format" : "uri",
            "example" : "https://test.api.amadeus.com/v1/area/resources?..."
          }
        },
        "example" : {
          "self" : "https://test.api.amadeus.com/v1/area/resources?param=value"
        }
      },
      "CollectionMeta" : {
        "title" : "CollectionMeta",
        "type" : "object",
        "properties" : {
          "count" : {
            "type" : "integer",
            "example" : 1
          },
          "links" : {
            "$ref" : "#/components/schemas/CollectionLinks"
          }
        }
      },
      "Error" : {
        "required" : [ "code", "status", "title" ],
        "type" : "object",
        "properties" : {
          "code" : {
            "type" : "integer",
            "description" : "A machine-readable error code from the Amadeus Canned Messages table, that will enable the API Consumers code to handle this type of error"
          },
          "detail" : {
            "type" : "string",
            "description" : "An easy-to-read explanation specific to this occurrence of the problem. It should give the API consumer an idea of what went wrong and how to recover from it. Like the title, this field’s value can be localized."
          },
          "documentation" : {
            "type" : "string",
            "description" : "A link to a web page or file with further documentation to help the API consumer resolve this error",
            "format" : "url"
          },
          "source" : {
            "$ref" : "#/components/schemas/ErrorSource"
          },
          "status" : {
            "type" : "integer",
            "description" : "The [HTTP status code](https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml) of this response. This is present only in terminal errors which cause an unsuccessful response. In the case of multiple errors, they must all have the same status."
          },
          "title" : {
            "type" : "string",
            "description" : "An error title from the Canned Messages table with a 1:1 correspondence to the error code. This may be localized"
          }
        }
      },
      "Error400" : {
        "required" : [ "errors" ],
        "type" : "object",
        "properties" : {
          "errors" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/Error"
            }
          }
        }
      },
      "Error401" : {
        "required" : [ "errors" ],
        "type" : "object",
        "properties" : {
          "errors" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/Error"
            }
          }
        },
        "example" : {
          "errors" : [ {
            "code" : 20,
            "detail" : "Query unauthorized",
            "status" : 401,
            "title" : "RESTRICTED"
          } ]
        }
      },
      "Error500" : {
        "required" : [ "errors" ],
        "type" : "object",
        "properties" : {
          "errors" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/Error"
            }
          }
        },
        "example" : {
          "errors" : [ {
            "code" : 141,
            "status" : 500,
            "title" : "SYSTEM ERROR HAS OCCURRED"
          } ]
        }
      },
      "ErrorSource" : {
        "type" : "object",
        "properties" : {
          "example" : {
            "type" : "string",
            "description" : "A sample input to guide the user when resolving this issue"
          },
          "parameter" : {
            "type" : "string",
            "description" : "The key of the URI path or query parameter that caused the error"
          },
          "pointer" : {
            "type" : "string",
            "description" : "A JSON Pointer [RFC6901] to the associated entity in the request body that caused this error"
          }
        }
      },
      "HotelSentiment" : {
        "required" : [ "hotelId", "numberOfRatings", "numberOfReviews", "overallRating" ],
        "type" : "object",
        "properties" : {
          "hotelId" : {
            "type" : "string",
            "description" : "Amadeus Hotel Ids are found in the Hotel Search response (parameter name is 'hotelId')",
            "example" : "BBLONBTL"
          },
          "numberOfRatings" : {
            "type" : "integer",
            "example" : 350
          },
          "numberOfReviews" : {
            "type" : "integer",
            "example" : 200
          },
          "overallRating" : {
            "$ref" : "#/components/schemas/Score"
          },
          "sentiments" : {
            "type" : "object",
            "properties" : {
              "catering" : {
                "$ref" : "#/components/schemas/Score"
              },
              "facilities" : {
                "$ref" : "#/components/schemas/Score"
              },
              "internet" : {
                "$ref" : "#/components/schemas/Score"
              },
              "location" : {
                "$ref" : "#/components/schemas/Score"
              },
              "pointsOfInterest" : {
                "$ref" : "#/components/schemas/Score"
              },
              "roomComforts" : {
                "$ref" : "#/components/schemas/Score"
              },
              "service" : {
                "$ref" : "#/components/schemas/Score"
              },
              "sleepQuality" : {
                "$ref" : "#/components/schemas/Score"
              },
              "staff" : {
                "$ref" : "#/components/schemas/Score"
              },
              "swimmingPool" : {
                "$ref" : "#/components/schemas/Score"
              },
              "valueForMoney" : {
                "$ref" : "#/components/schemas/Score"
              }
            },
            "description" : "Dictionary containing scores for all the available categories.  If a property does not have any category this object will not be present in the response."
          },
          "type" : {
            "type" : "string",
            "example" : "hotelSentiment"
          }
        }
      },
      "Score" : {
        "type" : "integer",
        "description" : "Integer between 0 and 100. It represents the score for a specific category or the overall rating for a given Hotel.",
        "example" : 82
      },
      "Warning" : {
        "required" : [ "code", "title" ],
        "type" : "object",
        "properties" : {
          "code" : {
            "type" : "integer",
            "description" : "A machine-readable error code from the Canned Messages table, that will enable the API Consumers code to handle this type of error"
          },
          "detail" : {
            "type" : "string",
            "description" : "An easy-to-read explanation specific to this occurrence of the problem. It should give the API consumer an idea of what went wrong and how to recover from it. Like the title, this field’s value can be localized."
          },
          "documentation" : {
            "type" : "string",
            "description" : "A link to a web page or file with further documentation to help the API consumer resolve this error",
            "format" : "url"
          },
          "source" : {
            "$ref" : "#/components/schemas/ErrorSource"
          },
          "title" : {
            "type" : "string",
            "description" : "An error title from the Canned Messages table with a 1:1 correspondence to the error code. This may be localized"
          }
        }
      },
      "WarningNotFound" : {
        "allOf" : [ {
          "$ref" : "#/components/schemas/Warning"
        } ]
      }
    },
    "responses" : {
      "400" : {
        "description" : "Not Found",
        "content" : {
          "application/vnd.amadeus+json" : {
            "schema" : {
              "$ref" : "#/components/schemas/Error400"
            }
          }
        }
      },
      "401" : {
        "description" : "Unauthorized",
        "content" : {
          "application/vnd.amadeus+json" : {
            "schema" : {
              "$ref" : "#/components/schemas/Error401"
            }
          }
        }
      },
      "500" : {
        "description" : "Unexpected Error",
        "content" : {
          "application/vnd.amadeus+json" : {
            "schema" : {
              "$ref" : "#/components/schemas/Error500"
            }
          }
        }
      },
      "sentiments" : {
        "description" : "Successful operation",
        "content" : {
          "application/vnd.amadeus+json" : {
            "schema" : {
              "title" : "SuccessSentiments",
              "type" : "object",
              "example" : {
                "data" : [ {
                  "hotelId" : "ADNYCCTB",
                  "numberOfRatings" : 278,
                  "numberOfReviews" : 218,
                  "overallRating" : 93,
                  "sentiments" : {
                    "catering" : 89,
                    "facilities" : 90,
                    "location" : 98,
                    "pointsOfInterest" : 91,
                    "roomComforts" : 92,
                    "service" : 98,
                    "sleepQuality" : 87,
                    "staff" : 100,
                    "valueForMoney" : 87
                  },
                  "type" : "hotelSentiment"
                }, {
                  "hotelId" : "TELONMFS",
                  "numberOfRatings" : 2666,
                  "numberOfReviews" : 2667,
                  "overallRating" : 81,
                  "sentiments" : {
                    "catering" : 81,
                    "facilities" : 75,
                    "internet" : 72,
                    "location" : 89,
                    "pointsOfInterest" : 81,
                    "roomComforts" : 87,
                    "service" : 80,
                    "sleepQuality" : 78,
                    "staff" : 89,
                    "valueForMoney" : 75
                  },
                  "type" : "hotelSentiment"
                } ],
                "meta" : {
                  "count" : 1,
                  "links" : {
                    "self" : "https://test.api.amadeus.com/v2/e-reputation/hotel-sentiments?hotelIds=ADNYCCTB,TELONMFS,XXXYYY01"
                  }
                },
                "warnings" : [ {
                  "code" : 913,
                  "detail" : "Some of the requested properties were not found in our database.",
                  "source" : {
                    "parameter" : "hotelIds",
                    "pointer" : "XXXYYY01"
                  },
                  "title" : "PROPERTIES NOT FOUND"
                } ]
              }
            }
          }
        }
      }
    }
  }
}