{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "On-Demand Flight Status",
    "description" : "\nBefore using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization-262)** for more information on how to generate an access token. \n  \nPlease also be aware that our test environment is based on a subset of the production, to see what is included in test please refer to our **[data collection](https://github.com/amadeus4dev/data-collection)**.\n",
    "version" : "2.0.2"
  },
  "servers" : [ {
    "url" : "https://test.api.amadeus.com/v2"
  } ],
  "paths" : {
    "/schedule/flights" : {
      "get" : {
        "tags" : [ "flights" ],
        "summary" : "Retrieves a unique flight by search criteria.",
        "operationId" : "getFlightsStatus",
        "parameters" : [ {
          "name" : "carrierCode",
          "in" : "query",
          "description" : "2 to 3-character IATA carrier code ([IATA table codes](http://www.iata.org/publications/Pages/code-search.aspx)).\n",
          "required" : true,
          "schema" : {
            "type" : "string"
          },
          "example" : "TP"
        }, {
          "name" : "flightNumber",
          "in" : "query",
          "description" : "1 to 4-digit number of the flight. e.g. 4537",
          "required" : true,
          "schema" : {
            "type" : "string"
          },
          "example" : "487"
        }, {
          "name" : "scheduledDepartureDate",
          "in" : "query",
          "description" : "scheduled departure date of the flight, local to the departure airport, format YYYY-MM-DD.",
          "required" : true,
          "schema" : {
            "type" : "string",
            "format" : "date"
          },
          "example" : "2023-08-01"
        }, {
          "name" : "operationalSuffix",
          "in" : "query",
          "description" : "1-letter operational suffix assigned by the carrier to differentiate flight in case of delay changing the departure date e.g. A\n",
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "A list of dated flights",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "title" : "Success Flights.",
                  "type" : "object",
                  "example" : {
                    "data" : [ {
                      "flightDesignator" : {
                        "carrierCode" : "TP",
                        "flightNumber" : 487
                      },
                      "flightPoints" : [ {
                        "departure" : {
                          "timings" : [ {
                            "qualifier" : "STD",
                            "value" : "2023-08-01T18:10+02:00"
                          } ]
                        },
                        "iataCode" : "NCE"
                      }, {
                        "arrival" : {
                          "timings" : [ {
                            "qualifier" : "STA",
                            "value" : "2023-08-01T19:45+01:00"
                          } ]
                        },
                        "iataCode" : "LIS"
                      } ],
                      "legs" : [ {
                        "aircraftEquipment" : {
                          "aircraftType" : "E90"
                        },
                        "boardPointIataCode" : "NCE",
                        "offPointIataCode" : "LIS",
                        "scheduledLegDuration" : "PT2H35M"
                      } ],
                      "scheduledDepartureDate" : "2023-08-01",
                      "segments" : [ {
                        "boardPointIataCode" : "NCE",
                        "offPointIataCode" : "LIS",
                        "partnership" : {
                          "operatingFlight" : {
                            "carrierCode" : "A3",
                            "flightNumber" : 1748
                          }
                        },
                        "scheduledSegmentDuration" : "PT2H35M"
                      } ],
                      "type" : "DatedFlight"
                    } ],
                    "meta" : {
                      "count" : 1,
                      "links" : {
                        "self" : "https://test.api.amadeus.com/v2/schedule/flights?carrierCode=TP&flightNumber=487&scheduledDepartureDate=2023-08-01"
                      }
                    }
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "code    | title\n------- | -------------------------------------\n477     | INVALID FORMAT\n572     | INVALID OPTION\n2781    | INVALID LENGTH\n4926    | INVALID DATA RECEIVED\n32171   | MANDATORY DATA MISSING\n",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error_400"
                }
              }
            }
          },
          "401" : {
            "description" : "Unauthorized",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error_401"
                }
              }
            }
          },
          "default" : {
            "description" : "Unexpected Error",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error_500"
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "AircraftEquipment" : {
        "type" : "object",
        "properties" : {
          "aircraftType" : {
            "type" : "string",
            "description" : "the type of aircraft that will operate the leg",
            "example" : "733"
          }
        }
      },
      "Arrival" : {
        "type" : "object",
        "properties" : {
          "gate" : {
            "$ref" : "#/components/schemas/Gate"
          },
          "terminal" : {
            "$ref" : "#/components/schemas/Terminal"
          },
          "timings" : {
            "type" : "array",
            "description" : "the list of timings",
            "items" : {
              "$ref" : "#/components/schemas/Timing"
            }
          }
        }
      },
      "Collection_Meta" : {
        "title" : "Collection_Meta",
        "type" : "object",
        "properties" : {
          "count" : {
            "type" : "integer",
            "example" : 1
          },
          "links" : {
            "title" : "CollectionLinks",
            "type" : "object",
            "properties" : {
              "first" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              },
              "last" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              },
              "next" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              },
              "previous" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              },
              "self" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              },
              "up" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              }
            },
            "example" : {
              "self" : "https://test.api.amadeus.com/v1/area/resources?param=value"
            }
          }
        }
      },
      "DatedFlight" : {
        "type" : "object",
        "properties" : {
          "flightDesignator" : {
            "$ref" : "#/components/schemas/FlightDesignator"
          },
          "flightPoints" : {
            "type" : "array",
            "description" : "the flight points of the flight.\nAt least one departure, one arrival\n",
            "items" : {
              "$ref" : "#/components/schemas/FlightPoint"
            }
          },
          "legs" : {
            "type" : "array",
            "description" : "the list of legs of the datedFlight.\n- definition of leg: operation of the aircraft between a departure station and the next arrival station (between take off and landing)\n",
            "items" : {
              "$ref" : "#/components/schemas/Leg"
            }
          },
          "scheduledDepartureDate" : {
            "type" : "string",
            "description" : "the scheduled departure date",
            "format" : "date",
            "example" : 1541462400000
          },
          "segments" : {
            "type" : "array",
            "description" : "the list of segments of the datedFlight\n- definition of segment: the commercial unit corresponding to the passenger journey traveling between two points with the same flight (same flight designator)\n",
            "items" : {
              "$ref" : "#/components/schemas/Segment"
            }
          },
          "type" : {
            "type" : "string",
            "description" : "the resource name",
            "readOnly" : true
          }
        }
      },
      "Delay" : {
        "type" : "object",
        "properties" : {
          "duration" : {
            "type" : "string",
            "description" : "the delay recorded for the timing following [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Durations)",
            "example" : "PT25M"
          }
        }
      },
      "Departure" : {
        "type" : "object",
        "properties" : {
          "gate" : {
            "$ref" : "#/components/schemas/Gate"
          },
          "terminal" : {
            "$ref" : "#/components/schemas/Terminal"
          },
          "timings" : {
            "type" : "array",
            "description" : "the list of timings",
            "items" : {
              "$ref" : "#/components/schemas/Timing"
            }
          }
        }
      },
      "Error_400" : {
        "required" : [ "errors" ],
        "type" : "object",
        "properties" : {
          "errors" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/Issue"
            }
          }
        },
        "example" : {
          "errors" : [ {
            "code" : 477,
            "detail" : "invalid query parameter format",
            "source" : {
              "example" : "CDG",
              "parameter" : "airport"
            },
            "status" : 400,
            "title" : "INVALID FORMAT"
          } ]
        }
      },
      "Error_401" : {
        "required" : [ "errors" ],
        "type" : "object",
        "properties" : {
          "errors" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/Issue"
            }
          }
        },
        "example" : {
          "errors" : [ {
            "code" : 20,
            "detail" : "Query unauthorized",
            "status" : 401,
            "title" : "RESTRICTED"
          } ]
        }
      },
      "Error_500" : {
        "required" : [ "errors" ],
        "type" : "object",
        "properties" : {
          "errors" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/Issue"
            }
          }
        },
        "example" : {
          "errors" : [ {
            "code" : 141,
            "status" : 500,
            "title" : "SYSTEM ERROR HAS OCCURRED"
          } ]
        }
      },
      "FlightDesignator" : {
        "type" : "object",
        "properties" : {
          "carrierCode" : {
            "type" : "string",
            "description" : "2 to 3-character IATA code of the carrier. e.g. 6X"
          },
          "flightNumber" : {
            "type" : "integer",
            "description" : "1 to 4-digit number of the flight e.g. 4537",
            "format" : "int64"
          },
          "operationalSuffix" : {
            "type" : "string",
            "description" : "1-letter operational suffix of the flight e.g. A"
          }
        }
      },
      "FlightPoint" : {
        "type" : "object",
        "properties" : {
          "arrival" : {
            "$ref" : "#/components/schemas/Arrival"
          },
          "departure" : {
            "$ref" : "#/components/schemas/Departure"
          },
          "iataCode" : {
            "type" : "string",
            "description" : "3-letter IATA code of the airport. e.g. CDG",
            "example" : "CDG"
          }
        }
      },
      "Gate" : {
        "type" : "object",
        "properties" : {
          "mainGate" : {
            "type" : "string",
            "description" : "the main gate number",
            "example" : "10A"
          }
        }
      },
      "Issue" : {
        "type" : "object",
        "properties" : {
          "code" : {
            "type" : "integer",
            "description" : "an application-specific error code",
            "format" : "int64"
          },
          "detail" : {
            "type" : "string",
            "description" : "explanation of the error"
          },
          "source" : {
            "title" : "Issue_Source",
            "type" : "object",
            "properties" : {
              "example" : {
                "type" : "string",
                "description" : "a string indicating an example of the right value"
              },
              "parameter" : {
                "type" : "string",
                "description" : "a string indicating which URI query parameter caused the issue"
              },
              "pointer" : {
                "type" : "string",
                "description" : "a JSON Pointer [RFC6901] to the associated entity in the request document"
              }
            },
            "description" : "an object containing references to the source of the error"
          },
          "status" : {
            "type" : "integer",
            "description" : "the HTTP status code applicable to this error"
          },
          "title" : {
            "type" : "string",
            "description" : "a short summary of the error"
          }
        }
      },
      "Leg" : {
        "type" : "object",
        "properties" : {
          "aircraftEquipment" : {
            "$ref" : "#/components/schemas/AircraftEquipment"
          },
          "boardPointIataCode" : {
            "pattern" : "[a-zA-Z]{3}",
            "type" : "string",
            "description" : "3-letter IATA code of the departure airport. e.g. LHR",
            "example" : "LHR"
          },
          "offPointIataCode" : {
            "pattern" : "[a-zA-Z]{3}",
            "type" : "string",
            "description" : "3-letter IATA code of the arrival airport. e.g. BKK",
            "example" : "BKK"
          },
          "scheduledLegDuration" : {
            "type" : "string",
            "description" : "duration of the leg following standard [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Durations)",
            "example" : "PT14H50M"
          }
        }
      },
      "Partnership" : {
        "type" : "object",
        "properties" : {
          "operatingFlight" : {
            "$ref" : "#/components/schemas/FlightDesignator"
          }
        }
      },
      "Segment" : {
        "type" : "object",
        "properties" : {
          "boardPointIataCode" : {
            "pattern" : "[a-zA-Z]{3}",
            "type" : "string",
            "description" : "3-letter IATA code of the departure airport. e.g. CDG",
            "example" : "LHR"
          },
          "offPointIataCode" : {
            "pattern" : "[a-zA-Z]{3}",
            "type" : "string",
            "description" : "3-letter IATA code of the arrival airport. e.g. AMS",
            "example" : "BKK"
          },
          "partnership" : {
            "$ref" : "#/components/schemas/Partnership"
          },
          "scheduledSegmentDuration" : {
            "type" : "string",
            "description" : "duration of the segment following standard [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Durations)",
            "example" : "PT14H50M"
          }
        }
      },
      "Terminal" : {
        "type" : "object",
        "properties" : {
          "code" : {
            "type" : "string",
            "description" : "the code of the terminal",
            "example" : "1"
          }
        }
      },
      "Timing" : {
        "type" : "object",
        "properties" : {
          "delays" : {
            "type" : "array",
            "description" : "delays that might be recorded on a timing",
            "items" : {
              "$ref" : "#/components/schemas/Delay"
            }
          },
          "qualifier" : {
            "type" : "string",
            "description" : "the qualifier of the timing. e.g. STD (stands for Schedule Time Departure)",
            "example" : "STD"
          },
          "value" : {
            "type" : "string",
            "format" : "date-time"
          }
        }
      }
    },
    "responses" : {
      "400" : {
        "description" : "code    | title\n------- | -------------------------------------\n477     | INVALID FORMAT\n572     | INVALID OPTION\n2781    | INVALID LENGTH\n4926    | INVALID DATA RECEIVED\n32171   | MANDATORY DATA MISSING\n",
        "content" : {
          "application/vnd.amadeus+json" : {
            "schema" : {
              "$ref" : "#/components/schemas/Error_400"
            }
          }
        }
      },
      "401" : {
        "description" : "Unauthorized",
        "content" : {
          "application/vnd.amadeus+json" : {
            "schema" : {
              "$ref" : "#/components/schemas/Error_401"
            }
          }
        }
      },
      "500" : {
        "description" : "Unexpected Error",
        "content" : {
          "application/vnd.amadeus+json" : {
            "schema" : {
              "$ref" : "#/components/schemas/Error_500"
            }
          }
        }
      },
      "datedFlights" : {
        "description" : "A list of dated flights",
        "content" : {
          "application/vnd.amadeus+json" : {
            "schema" : {
              "title" : "Success Flights.",
              "type" : "object",
              "example" : {
                "data" : [ {
                  "flightDesignator" : {
                    "carrierCode" : "TP",
                    "flightNumber" : 487
                  },
                  "flightPoints" : [ {
                    "departure" : {
                      "timings" : [ {
                        "qualifier" : "STD",
                        "value" : "2023-08-01T18:10+02:00"
                      } ]
                    },
                    "iataCode" : "NCE"
                  }, {
                    "arrival" : {
                      "timings" : [ {
                        "qualifier" : "STA",
                        "value" : "2023-08-01T19:45+01:00"
                      } ]
                    },
                    "iataCode" : "LIS"
                  } ],
                  "legs" : [ {
                    "aircraftEquipment" : {
                      "aircraftType" : "E90"
                    },
                    "boardPointIataCode" : "NCE",
                    "offPointIataCode" : "LIS",
                    "scheduledLegDuration" : "PT2H35M"
                  } ],
                  "scheduledDepartureDate" : "2023-08-01",
                  "segments" : [ {
                    "boardPointIataCode" : "NCE",
                    "offPointIataCode" : "LIS",
                    "partnership" : {
                      "operatingFlight" : {
                        "carrierCode" : "A3",
                        "flightNumber" : 1748
                      }
                    },
                    "scheduledSegmentDuration" : "PT2H35M"
                  } ],
                  "type" : "DatedFlight"
                } ],
                "meta" : {
                  "count" : 1,
                  "links" : {
                    "self" : "https://test.api.amadeus.com/v2/schedule/flights?carrierCode=TP&flightNumber=487&scheduledDepartureDate=2023-08-01"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}