{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Safe Place",
    "description" : "\nBefore using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization-262)** for more information on how to generate an access token. \n  \nPlease also be aware that our test environment is based on a subset of the production, this API in test only returns a few selected cities. You can find the list in our **[data collection](https://github.com/amadeus4dev/data-collection)**.",
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "https://test.api.amadeus.com/v1"
  } ],
  "paths" : {
    "/safety/safety-rated-locations" : {
      "get" : {
        "tags" : [ "Search" ],
        "summary" : "Returns safety rating for a given location and radius.",
        "operationId" : "getSafetyRanking",
        "parameters" : [ {
          "name" : "latitude",
          "in" : "query",
          "description" : "Latitude (decimal coordinates)",
          "required" : true,
          "schema" : {
            "type" : "number",
            "format" : "double"
          },
          "example" : 41.397158
        }, {
          "name" : "longitude",
          "in" : "query",
          "description" : "Longitude (decimal coordinates)",
          "required" : true,
          "schema" : {
            "type" : "number",
            "format" : "double"
          },
          "example" : 2.160873
        }, {
          "name" : "radius",
          "in" : "query",
          "description" : "radius of the search in Kilometer. Can be from 0 to 20, default value is 1 Km.",
          "schema" : {
            "maximum" : 20,
            "minimum" : 0,
            "type" : "integer",
            "default" : 1
          }
        }, {
          "name" : "page[limit]",
          "in" : "query",
          "description" : "maximum items in one page",
          "schema" : {
            "type" : "integer",
            "default" : 10
          }
        }, {
          "name" : "page[offset]",
          "in" : "query",
          "description" : "start index of the requested page",
          "schema" : {
            "type" : "integer",
            "default" : 0
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful Operation",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "title" : "Success",
                  "type" : "object",
                  "example" : {
                    "data" : [ {
                      "geoCode" : {
                        "latitude" : 41.385064,
                        "longitude" : 2.173404
                      },
                      "id" : "Q930402719",
                      "name" : "Barcelona",
                      "safetyScores" : {
                        "lgbtq" : 39,
                        "medical" : 0,
                        "overall" : 45,
                        "physicalHarm" : 36,
                        "politicalFreedom" : 50,
                        "theft" : 44,
                        "women" : 34
                      },
                      "self" : {
                        "methods" : [ "GET" ],
                        "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402719"
                      },
                      "subType" : "CITY",
                      "type" : "safety-rated-location"
                    }, {
                      "geoCode" : {
                        "latitude" : 41.3885573,
                        "longitude" : 2.1573033
                      },
                      "id" : "Q930402720",
                      "name" : "Antiga Esquerra de l'Eixample (Barcelona)",
                      "safetyScores" : {
                        "lgbtq" : 37,
                        "medical" : 0,
                        "overall" : 44,
                        "physicalHarm" : 34,
                        "politicalFreedom" : 50,
                        "theft" : 42,
                        "women" : 33
                      },
                      "self" : {
                        "methods" : [ "GET" ],
                        "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402720"
                      },
                      "subType" : "DISTRICT",
                      "type" : "safety-rated-location"
                    }, {
                      "geoCode" : {
                        "latitude" : 41.412131,
                        "longitude" : 2.1683571
                      },
                      "id" : "Q930402721",
                      "name" : "Baix Guinardó (Barcelona)",
                      "safetyScores" : {
                        "lgbtq" : 37,
                        "medical" : 0,
                        "overall" : 44,
                        "physicalHarm" : 34,
                        "politicalFreedom" : 50,
                        "theft" : 42,
                        "women" : 33
                      },
                      "self" : {
                        "methods" : [ "GET" ],
                        "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402721"
                      },
                      "subType" : "DISTRICT",
                      "type" : "safety-rated-location"
                    }, {
                      "geoCode" : {
                        "latitude" : 41.380894,
                        "longitude" : 2.189385
                      },
                      "id" : "Q930402722",
                      "name" : "Barceloneta (Barcelona)",
                      "safetyScores" : {
                        "lgbtq" : 42,
                        "medical" : 0,
                        "overall" : 47,
                        "physicalHarm" : 39,
                        "politicalFreedom" : 50,
                        "theft" : 49,
                        "women" : 34
                      },
                      "self" : {
                        "methods" : [ "GET" ],
                        "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402722"
                      },
                      "subType" : "DISTRICT",
                      "type" : "safety-rated-location"
                    }, {
                      "geoCode" : {
                        "latitude" : 41.4172284,
                        "longitude" : 2.163444
                      },
                      "id" : "Q930402724",
                      "name" : "Can Baró (Barcelona)",
                      "safetyScores" : {
                        "lgbtq" : 37,
                        "medical" : 0,
                        "overall" : 44,
                        "physicalHarm" : 34,
                        "politicalFreedom" : 50,
                        "theft" : 42,
                        "women" : 33
                      },
                      "self" : {
                        "methods" : [ "GET" ],
                        "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402724"
                      },
                      "subType" : "DISTRICT",
                      "type" : "safety-rated-location"
                    }, {
                      "geoCode" : {
                        "latitude" : 41.384728,
                        "longitude" : 2.18286
                      },
                      "id" : "Q930402731",
                      "name" : "El Born (Barcelona)",
                      "safetyScores" : {
                        "lgbtq" : 42,
                        "medical" : 0,
                        "overall" : 47,
                        "physicalHarm" : 39,
                        "politicalFreedom" : 50,
                        "theft" : 49,
                        "women" : 34
                      },
                      "self" : {
                        "methods" : [ "GET" ],
                        "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402731"
                      },
                      "subType" : "DISTRICT",
                      "type" : "safety-rated-location"
                    }, {
                      "geoCode" : {
                        "latitude" : 41.4118532,
                        "longitude" : 2.1830997
                      },
                      "id" : "Q930402732",
                      "name" : "El Camp de l'Arpa del Clot (Barcelona)",
                      "safetyScores" : {
                        "lgbtq" : 37,
                        "medical" : 0,
                        "overall" : 45,
                        "physicalHarm" : 35,
                        "politicalFreedom" : 50,
                        "theft" : 43,
                        "women" : 33
                      },
                      "self" : {
                        "methods" : [ "GET" ],
                        "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402732"
                      },
                      "subType" : "DISTRICT",
                      "type" : "safety-rated-location"
                    }, {
                      "geoCode" : {
                        "latitude" : 41.4046685,
                        "longitude" : 2.1659005
                      },
                      "id" : "Q930402733",
                      "name" : "El Camp d'en Grassot i Gràcia Nova (Barcelona)",
                      "safetyScores" : {
                        "lgbtq" : 37,
                        "medical" : 0,
                        "overall" : 44,
                        "physicalHarm" : 34,
                        "politicalFreedom" : 50,
                        "theft" : 42,
                        "women" : 33
                      },
                      "self" : {
                        "methods" : [ "GET" ],
                        "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402733"
                      },
                      "subType" : "DISTRICT",
                      "type" : "safety-rated-location"
                    }, {
                      "geoCode" : {
                        "latitude" : 41.422371,
                        "longitude" : 2.1560753
                      },
                      "id" : "Q930402734",
                      "name" : "El Carmel (Barcelona)",
                      "safetyScores" : {
                        "lgbtq" : 37,
                        "medical" : 0,
                        "overall" : 44,
                        "physicalHarm" : 34,
                        "politicalFreedom" : 50,
                        "theft" : 42,
                        "women" : 33
                      },
                      "self" : {
                        "methods" : [ "GET" ],
                        "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402734"
                      },
                      "subType" : "DISTRICT",
                      "type" : "safety-rated-location"
                    }, {
                      "geoCode" : {
                        "latitude" : 41.4097037,
                        "longitude" : 2.1892366
                      },
                      "id" : "Q930402735",
                      "name" : "El Clot (Barcelona)",
                      "safetyScores" : {
                        "lgbtq" : 37,
                        "medical" : 0,
                        "overall" : 45,
                        "physicalHarm" : 35,
                        "politicalFreedom" : 50,
                        "theft" : 43,
                        "women" : 33
                      },
                      "self" : {
                        "methods" : [ "GET" ],
                        "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402735"
                      },
                      "subType" : "DISTRICT",
                      "type" : "safety-rated-location"
                    } ],
                    "meta" : {
                      "count" : 43,
                      "links" : {
                        "first" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations?latitude=41.397158&longitude=2.160873&page%5Boffset%5D=0&radius=2",
                        "last" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations?latitude=41.397158&longitude=2.160873&page%5Boffset%5D=4&radius=2",
                        "next" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations?latitude=41.397158&longitude=2.160873&page%5Boffset%5D=1&radius=2",
                        "self" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations?latitude=41.397158&longitude=2.160873&radius=2"
                      }
                    }
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "code    | title                                 \n------- | ------------------------------------- \n477     | INVALID FORMAT\n572     | INVALID OPTION\n4926    | INVALID DATA RECEIVED               \n32171   | MANDATORY DATA MISSING \t     \n",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error_400"
                }
              }
            }
          },
          "default" : {
            "description" : "Unexpected Error",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error_500"
                }
              }
            }
          }
        }
      }
    },
    "/safety/safety-rated-locations/by-square" : {
      "get" : {
        "tags" : [ "Search" ],
        "summary" : "Returns the safety rating of a given area",
        "operationId" : "getSafetyRankBySquare",
        "parameters" : [ {
          "name" : "north",
          "in" : "query",
          "description" : "Latitude north of bounding box (decimal coordinates)",
          "required" : true,
          "schema" : {
            "type" : "number",
            "format" : "double"
          },
          "example" : 41.397158
        }, {
          "name" : "west",
          "in" : "query",
          "description" : "Longitude west of bounding box (decimal coordinates)",
          "required" : true,
          "schema" : {
            "type" : "number",
            "format" : "double"
          },
          "example" : 2.160873
        }, {
          "name" : "south",
          "in" : "query",
          "description" : "Latitude south of bounding box (decimal coordinates)",
          "required" : true,
          "schema" : {
            "type" : "number",
            "format" : "double"
          },
          "example" : 41.394582
        }, {
          "name" : "east",
          "in" : "query",
          "description" : "Longitude east of bounding box (decimal coordinates)",
          "required" : true,
          "schema" : {
            "type" : "number",
            "format" : "double"
          },
          "example" : 2.177181
        }, {
          "name" : "page[limit]",
          "in" : "query",
          "description" : "maximum items in one page",
          "schema" : {
            "type" : "integer",
            "default" : 10
          }
        }, {
          "name" : "page[offset]",
          "in" : "query",
          "description" : "start index of the requested page",
          "schema" : {
            "type" : "integer",
            "default" : 0
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful Operation",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "title" : "Success",
                  "type" : "object",
                  "example" : {
                    "data" : [ {
                      "geoCode" : {
                        "latitude" : 41.385064,
                        "longitude" : 2.173404
                      },
                      "id" : "Q930402719",
                      "name" : "Barcelona",
                      "safetyScores" : {
                        "lgbtq" : 39,
                        "medical" : 0,
                        "overall" : 45,
                        "physicalHarm" : 36,
                        "politicalFreedom" : 50,
                        "theft" : 44,
                        "women" : 34
                      },
                      "self" : {
                        "methods" : [ "GET" ],
                        "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402719"
                      },
                      "subType" : "CITY",
                      "type" : "safety-rated-location"
                    }, {
                      "geoCode" : {
                        "latitude" : 41.3885573,
                        "longitude" : 2.1573033
                      },
                      "id" : "Q930402720",
                      "name" : "Antiga Esquerra de l'Eixample (Barcelona)",
                      "safetyScores" : {
                        "lgbtq" : 37,
                        "medical" : 0,
                        "overall" : 44,
                        "physicalHarm" : 34,
                        "politicalFreedom" : 50,
                        "theft" : 42,
                        "women" : 33
                      },
                      "self" : {
                        "methods" : [ "GET" ],
                        "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402720"
                      },
                      "subType" : "DISTRICT",
                      "type" : "safety-rated-location"
                    }, {
                      "geoCode" : {
                        "latitude" : 41.412131,
                        "longitude" : 2.1683571
                      },
                      "id" : "Q930402721",
                      "name" : "Baix Guinardó (Barcelona)",
                      "safetyScores" : {
                        "lgbtq" : 37,
                        "medical" : 0,
                        "overall" : 44,
                        "physicalHarm" : 34,
                        "politicalFreedom" : 50,
                        "theft" : 42,
                        "women" : 33
                      },
                      "self" : {
                        "methods" : [ "GET" ],
                        "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402721"
                      },
                      "subType" : "DISTRICT",
                      "type" : "safety-rated-location"
                    }, {
                      "geoCode" : {
                        "latitude" : 41.380894,
                        "longitude" : 2.189385
                      },
                      "id" : "Q930402722",
                      "name" : "Barceloneta (Barcelona)",
                      "safetyScores" : {
                        "lgbtq" : 42,
                        "medical" : 0,
                        "overall" : 47,
                        "physicalHarm" : 39,
                        "politicalFreedom" : 50,
                        "theft" : 49,
                        "women" : 34
                      },
                      "self" : {
                        "methods" : [ "GET" ],
                        "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402722"
                      },
                      "subType" : "DISTRICT",
                      "type" : "safety-rated-location"
                    }, {
                      "geoCode" : {
                        "latitude" : 41.4172284,
                        "longitude" : 2.163444
                      },
                      "id" : "Q930402724",
                      "name" : "Can Baró (Barcelona)",
                      "safetyScores" : {
                        "lgbtq" : 37,
                        "medical" : 0,
                        "overall" : 44,
                        "physicalHarm" : 34,
                        "politicalFreedom" : 50,
                        "theft" : 42,
                        "women" : 33
                      },
                      "self" : {
                        "methods" : [ "GET" ],
                        "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402724"
                      },
                      "subType" : "DISTRICT",
                      "type" : "safety-rated-location"
                    }, {
                      "geoCode" : {
                        "latitude" : 41.384728,
                        "longitude" : 2.18286
                      },
                      "id" : "Q930402731",
                      "name" : "El Born (Barcelona)",
                      "safetyScores" : {
                        "lgbtq" : 42,
                        "medical" : 0,
                        "overall" : 47,
                        "physicalHarm" : 39,
                        "politicalFreedom" : 50,
                        "theft" : 49,
                        "women" : 34
                      },
                      "self" : {
                        "methods" : [ "GET" ],
                        "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402731"
                      },
                      "subType" : "DISTRICT",
                      "type" : "safety-rated-location"
                    }, {
                      "geoCode" : {
                        "latitude" : 41.4118532,
                        "longitude" : 2.1830997
                      },
                      "id" : "Q930402732",
                      "name" : "El Camp de l'Arpa del Clot (Barcelona)",
                      "safetyScores" : {
                        "lgbtq" : 37,
                        "medical" : 0,
                        "overall" : 45,
                        "physicalHarm" : 35,
                        "politicalFreedom" : 50,
                        "theft" : 43,
                        "women" : 33
                      },
                      "self" : {
                        "methods" : [ "GET" ],
                        "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402732"
                      },
                      "subType" : "DISTRICT",
                      "type" : "safety-rated-location"
                    }, {
                      "geoCode" : {
                        "latitude" : 41.4046685,
                        "longitude" : 2.1659005
                      },
                      "id" : "Q930402733",
                      "name" : "El Camp d'en Grassot i Gràcia Nova (Barcelona)",
                      "safetyScores" : {
                        "lgbtq" : 37,
                        "medical" : 0,
                        "overall" : 44,
                        "physicalHarm" : 34,
                        "politicalFreedom" : 50,
                        "theft" : 42,
                        "women" : 33
                      },
                      "self" : {
                        "methods" : [ "GET" ],
                        "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402733"
                      },
                      "subType" : "DISTRICT",
                      "type" : "safety-rated-location"
                    }, {
                      "geoCode" : {
                        "latitude" : 41.422371,
                        "longitude" : 2.1560753
                      },
                      "id" : "Q930402734",
                      "name" : "El Carmel (Barcelona)",
                      "safetyScores" : {
                        "lgbtq" : 37,
                        "medical" : 0,
                        "overall" : 44,
                        "physicalHarm" : 34,
                        "politicalFreedom" : 50,
                        "theft" : 42,
                        "women" : 33
                      },
                      "self" : {
                        "methods" : [ "GET" ],
                        "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402734"
                      },
                      "subType" : "DISTRICT",
                      "type" : "safety-rated-location"
                    }, {
                      "geoCode" : {
                        "latitude" : 41.4097037,
                        "longitude" : 2.1892366
                      },
                      "id" : "Q930402735",
                      "name" : "El Clot (Barcelona)",
                      "safetyScores" : {
                        "lgbtq" : 37,
                        "medical" : 0,
                        "overall" : 45,
                        "physicalHarm" : 35,
                        "politicalFreedom" : 50,
                        "theft" : 43,
                        "women" : 33
                      },
                      "self" : {
                        "methods" : [ "GET" ],
                        "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402735"
                      },
                      "subType" : "DISTRICT",
                      "type" : "safety-rated-location"
                    } ],
                    "meta" : {
                      "count" : 43,
                      "links" : {
                        "first" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations?latitude=41.397158&longitude=2.160873&page%5Boffset%5D=0&radius=2",
                        "last" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations?latitude=41.397158&longitude=2.160873&page%5Boffset%5D=4&radius=2",
                        "next" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations?latitude=41.397158&longitude=2.160873&page%5Boffset%5D=1&radius=2",
                        "self" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations?latitude=41.397158&longitude=2.160873&radius=2"
                      }
                    }
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "code    | title                                 \n------- | ------------------------------------- \n477     | INVALID FORMAT\n572     | INVALID OPTION\n4926    | INVALID DATA RECEIVED               \n32171   | MANDATORY DATA MISSING \t     \n",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error_400"
                }
              }
            }
          },
          "default" : {
            "description" : "Unexpected Error",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error_500"
                }
              }
            }
          }
        }
      }
    },
    "/safety/safety-rated-locations/{safety-rated-locationId}" : {
      "get" : {
        "tags" : [ "Retrieve" ],
        "summary" : "Retieve safety information of a location by its Id.",
        "operationId" : "getLocationSafetyRanking",
        "parameters" : [ {
          "name" : "safety-rated-locationId",
          "in" : "path",
          "description" : "identifier of the location",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful Operation",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "title" : "Success",
                  "type" : "object",
                  "example" : {
                    "data" : [ {
                      "geoCode" : {
                        "latitude" : 41.385064,
                        "longitude" : 2.173404
                      },
                      "id" : "Q930402719",
                      "name" : "Barcelona",
                      "safetyScores" : {
                        "lgbtq" : 39,
                        "medical" : 0,
                        "overall" : 45,
                        "physicalHarm" : 36,
                        "politicalFreedom" : 50,
                        "theft" : 44,
                        "women" : 34
                      },
                      "self" : {
                        "methods" : [ "GET" ],
                        "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402719"
                      },
                      "subType" : "CITY",
                      "type" : "safety-rated-location"
                    } ],
                    "meta" : {
                      "links" : {
                        "self" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402719"
                      }
                    }
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "code    | title                                 \n------- | ------------------------------------- \n477     | INVALID FORMAT\n572     | INVALID OPTION\n4926    | INVALID DATA RECEIVED               \n32171   | MANDATORY DATA MISSING \t     \n",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error_400"
                }
              }
            }
          },
          "404" : {
            "description" : "Not Found",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error_404"
                }
              }
            }
          },
          "default" : {
            "description" : "Unexpected Error",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error_500"
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "Collection_Meta" : {
        "title" : "Collection_Meta",
        "type" : "object",
        "properties" : {
          "count" : {
            "type" : "integer",
            "example" : 1
          },
          "links" : {
            "title" : "CollectionLinks",
            "type" : "object",
            "properties" : {
              "first" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              },
              "last" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              },
              "next" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              },
              "previous" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              },
              "self" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              },
              "up" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              }
            },
            "example" : {
              "self" : "https://test.api.amadeus.com/v1/area/resources?param=value"
            }
          }
        }
      },
      "Error_400" : {
        "required" : [ "errors" ],
        "type" : "object",
        "properties" : {
          "errors" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/Issue"
            }
          }
        },
        "example" : {
          "errors" : [ {
            "code" : 477,
            "detail" : "invalid query parameter format",
            "source" : {
              "example" : "CDG",
              "parameter" : "airport"
            },
            "status" : 400,
            "title" : "INVALID FORMAT"
          } ]
        }
      },
      "Error_404" : {
        "required" : [ "errors" ],
        "type" : "object",
        "properties" : {
          "errors" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/Issue"
            }
          }
        },
        "example" : {
          "errors" : [ {
            "code" : 1797,
            "detail" : "no response found for this query parameter",
            "source" : {
              "parameter" : "airport"
            },
            "status" : 404,
            "title" : "NOT FOUND"
          } ]
        }
      },
      "Error_500" : {
        "required" : [ "errors" ],
        "type" : "object",
        "properties" : {
          "errors" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/Issue"
            }
          }
        },
        "example" : {
          "errors" : [ {
            "code" : 141,
            "status" : 500,
            "title" : "SYSTEM ERROR HAS OCCURRED"
          } ]
        }
      },
      "GeoCode" : {
        "type" : "object",
        "properties" : {
          "latitude" : {
            "type" : "number",
            "description" : "latitude of the location",
            "format" : "double",
            "example" : 43.580418
          },
          "longitude" : {
            "type" : "number",
            "description" : "longitude of the location",
            "format" : "double",
            "example" : 7.125102
          }
        }
      },
      "Issue" : {
        "type" : "object",
        "properties" : {
          "code" : {
            "type" : "integer",
            "description" : "an application-specific error code",
            "format" : "int64"
          },
          "detail" : {
            "type" : "string",
            "description" : "explanation of the error"
          },
          "source" : {
            "title" : "Issue_Source",
            "type" : "object",
            "properties" : {
              "example" : {
                "type" : "string",
                "description" : "a string indicating an example of the right value"
              },
              "parameter" : {
                "type" : "string",
                "description" : "a string indicating which URI query parameter caused the issue"
              },
              "pointer" : {
                "type" : "string",
                "description" : "a JSON Pointer [RFC6901] to the associated entity in the request document"
              }
            },
            "description" : "an object containing references to the source of the error"
          },
          "status" : {
            "type" : "integer",
            "description" : "the HTTP status code applicable to this error"
          },
          "title" : {
            "type" : "string",
            "description" : "a short summary of the error"
          }
        }
      },
      "Links" : {
        "required" : [ "href" ],
        "type" : "object",
        "properties" : {
          "count" : {
            "type" : "integer"
          },
          "href" : {
            "type" : "string",
            "format" : "uri"
          },
          "methods" : {
            "type" : "array",
            "items" : {
              "type" : "string",
              "enum" : [ "GET", "PUT", "DELETE", "POST", "PATCH" ]
            }
          }
        },
        "example" : {
          "href" : "string"
        }
      },
      "Location" : {
        "type" : "object",
        "properties" : {
          "geoCode" : {
            "$ref" : "#/components/schemas/GeoCode"
          },
          "id" : {
            "type" : "string",
            "description" : "id of the ressource"
          },
          "name" : {
            "type" : "string",
            "description" : "short name of the location",
            "example" : "Paris CDG"
          },
          "self" : {
            "$ref" : "#/components/schemas/Links"
          },
          "subType" : {
            "type" : "string",
            "description" : "location sub type",
            "example" : "AIRPORT",
            "enum" : [ "AIRPORT", "CITY", "POINT_OF_INTEREST", "DISTRICT" ]
          },
          "type" : {
            "type" : "string",
            "description" : "the resource name",
            "example" : "location"
          }
        }
      },
      "SafetyRatedLocation" : {
        "title" : "SafetyRatedLocation",
        "allOf" : [ {
          "type" : "object",
          "properties" : {
            "safetyScore" : {
              "$ref" : "#/components/schemas/SafetyScore"
            }
          }
        }, {
          "$ref" : "#/components/schemas/Location"
        } ]
      },
      "SafetyScore" : {
        "type" : "object",
        "properties" : {
          "lgbtq" : {
            "type" : "integer",
            "description" : "Likelihood of harm or discrimination against LGBTQ persons or groups and level of caution required at location. Score go from 1 (not likely) to 100 (very likely)."
          },
          "medical" : {
            "type" : "integer",
            "description" : "Likelihood of illness or disease, assessment of water and air quality, and access to reliable medical care. Score go from 1 (not likely) to 100 (very likely)."
          },
          "overall" : {
            "type" : "integer",
            "description" : "An average of the 6 “sub”-categories. Score go from 1 (very safe) to 100 (very dangerous)."
          },
          "physicalHarm" : {
            "type" : "integer",
            "description" : "Likelihood of injury due to harmful intent. Score go from 1 (not likely) to 100 (very likely)."
          },
          "politicalFreedom" : {
            "type" : "integer",
            "description" : "Potential for infringement of political rights or political unrest. Score go from 1 (not likely) to 100 (very likely)."
          },
          "theft" : {
            "type" : "integer",
            "description" : "Likelihood of theft. Score go from 1 (not likely) to 100 (very likely)."
          },
          "women" : {
            "type" : "integer",
            "description" : "Likelihood of inappropriate behavior against females. Score go from 1 (not likely) to 100 (very likely)."
          }
        }
      }
    },
    "responses" : {
      "400" : {
        "description" : "code    | title                                 \n------- | ------------------------------------- \n477     | INVALID FORMAT\n572     | INVALID OPTION\n4926    | INVALID DATA RECEIVED               \n32171   | MANDATORY DATA MISSING \t     \n",
        "content" : {
          "application/vnd.amadeus+json" : {
            "schema" : {
              "$ref" : "#/components/schemas/Error_400"
            }
          }
        }
      },
      "404" : {
        "description" : "Not Found",
        "content" : {
          "application/vnd.amadeus+json" : {
            "schema" : {
              "$ref" : "#/components/schemas/Error_404"
            }
          }
        }
      },
      "500" : {
        "description" : "Unexpected Error",
        "content" : {
          "application/vnd.amadeus+json" : {
            "schema" : {
              "$ref" : "#/components/schemas/Error_500"
            }
          }
        }
      },
      "safety-rated-location" : {
        "description" : "Successful Operation",
        "content" : {
          "application/vnd.amadeus+json" : {
            "schema" : {
              "title" : "Success",
              "type" : "object",
              "example" : {
                "data" : [ {
                  "geoCode" : {
                    "latitude" : 41.385064,
                    "longitude" : 2.173404
                  },
                  "id" : "Q930402719",
                  "name" : "Barcelona",
                  "safetyScores" : {
                    "lgbtq" : 39,
                    "medical" : 0,
                    "overall" : 45,
                    "physicalHarm" : 36,
                    "politicalFreedom" : 50,
                    "theft" : 44,
                    "women" : 34
                  },
                  "self" : {
                    "methods" : [ "GET" ],
                    "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402719"
                  },
                  "subType" : "CITY",
                  "type" : "safety-rated-location"
                } ],
                "meta" : {
                  "links" : {
                    "self" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402719"
                  }
                }
              }
            }
          }
        }
      },
      "safety-rated-locations" : {
        "description" : "Successful Operation",
        "content" : {
          "application/vnd.amadeus+json" : {
            "schema" : {
              "title" : "Success",
              "type" : "object",
              "example" : {
                "data" : [ {
                  "geoCode" : {
                    "latitude" : 41.385064,
                    "longitude" : 2.173404
                  },
                  "id" : "Q930402719",
                  "name" : "Barcelona",
                  "safetyScores" : {
                    "lgbtq" : 39,
                    "medical" : 0,
                    "overall" : 45,
                    "physicalHarm" : 36,
                    "politicalFreedom" : 50,
                    "theft" : 44,
                    "women" : 34
                  },
                  "self" : {
                    "methods" : [ "GET" ],
                    "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402719"
                  },
                  "subType" : "CITY",
                  "type" : "safety-rated-location"
                }, {
                  "geoCode" : {
                    "latitude" : 41.3885573,
                    "longitude" : 2.1573033
                  },
                  "id" : "Q930402720",
                  "name" : "Antiga Esquerra de l'Eixample (Barcelona)",
                  "safetyScores" : {
                    "lgbtq" : 37,
                    "medical" : 0,
                    "overall" : 44,
                    "physicalHarm" : 34,
                    "politicalFreedom" : 50,
                    "theft" : 42,
                    "women" : 33
                  },
                  "self" : {
                    "methods" : [ "GET" ],
                    "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402720"
                  },
                  "subType" : "DISTRICT",
                  "type" : "safety-rated-location"
                }, {
                  "geoCode" : {
                    "latitude" : 41.412131,
                    "longitude" : 2.1683571
                  },
                  "id" : "Q930402721",
                  "name" : "Baix Guinardó (Barcelona)",
                  "safetyScores" : {
                    "lgbtq" : 37,
                    "medical" : 0,
                    "overall" : 44,
                    "physicalHarm" : 34,
                    "politicalFreedom" : 50,
                    "theft" : 42,
                    "women" : 33
                  },
                  "self" : {
                    "methods" : [ "GET" ],
                    "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402721"
                  },
                  "subType" : "DISTRICT",
                  "type" : "safety-rated-location"
                }, {
                  "geoCode" : {
                    "latitude" : 41.380894,
                    "longitude" : 2.189385
                  },
                  "id" : "Q930402722",
                  "name" : "Barceloneta (Barcelona)",
                  "safetyScores" : {
                    "lgbtq" : 42,
                    "medical" : 0,
                    "overall" : 47,
                    "physicalHarm" : 39,
                    "politicalFreedom" : 50,
                    "theft" : 49,
                    "women" : 34
                  },
                  "self" : {
                    "methods" : [ "GET" ],
                    "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402722"
                  },
                  "subType" : "DISTRICT",
                  "type" : "safety-rated-location"
                }, {
                  "geoCode" : {
                    "latitude" : 41.4172284,
                    "longitude" : 2.163444
                  },
                  "id" : "Q930402724",
                  "name" : "Can Baró (Barcelona)",
                  "safetyScores" : {
                    "lgbtq" : 37,
                    "medical" : 0,
                    "overall" : 44,
                    "physicalHarm" : 34,
                    "politicalFreedom" : 50,
                    "theft" : 42,
                    "women" : 33
                  },
                  "self" : {
                    "methods" : [ "GET" ],
                    "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402724"
                  },
                  "subType" : "DISTRICT",
                  "type" : "safety-rated-location"
                }, {
                  "geoCode" : {
                    "latitude" : 41.384728,
                    "longitude" : 2.18286
                  },
                  "id" : "Q930402731",
                  "name" : "El Born (Barcelona)",
                  "safetyScores" : {
                    "lgbtq" : 42,
                    "medical" : 0,
                    "overall" : 47,
                    "physicalHarm" : 39,
                    "politicalFreedom" : 50,
                    "theft" : 49,
                    "women" : 34
                  },
                  "self" : {
                    "methods" : [ "GET" ],
                    "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402731"
                  },
                  "subType" : "DISTRICT",
                  "type" : "safety-rated-location"
                }, {
                  "geoCode" : {
                    "latitude" : 41.4118532,
                    "longitude" : 2.1830997
                  },
                  "id" : "Q930402732",
                  "name" : "El Camp de l'Arpa del Clot (Barcelona)",
                  "safetyScores" : {
                    "lgbtq" : 37,
                    "medical" : 0,
                    "overall" : 45,
                    "physicalHarm" : 35,
                    "politicalFreedom" : 50,
                    "theft" : 43,
                    "women" : 33
                  },
                  "self" : {
                    "methods" : [ "GET" ],
                    "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402732"
                  },
                  "subType" : "DISTRICT",
                  "type" : "safety-rated-location"
                }, {
                  "geoCode" : {
                    "latitude" : 41.4046685,
                    "longitude" : 2.1659005
                  },
                  "id" : "Q930402733",
                  "name" : "El Camp d'en Grassot i Gràcia Nova (Barcelona)",
                  "safetyScores" : {
                    "lgbtq" : 37,
                    "medical" : 0,
                    "overall" : 44,
                    "physicalHarm" : 34,
                    "politicalFreedom" : 50,
                    "theft" : 42,
                    "women" : 33
                  },
                  "self" : {
                    "methods" : [ "GET" ],
                    "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402733"
                  },
                  "subType" : "DISTRICT",
                  "type" : "safety-rated-location"
                }, {
                  "geoCode" : {
                    "latitude" : 41.422371,
                    "longitude" : 2.1560753
                  },
                  "id" : "Q930402734",
                  "name" : "El Carmel (Barcelona)",
                  "safetyScores" : {
                    "lgbtq" : 37,
                    "medical" : 0,
                    "overall" : 44,
                    "physicalHarm" : 34,
                    "politicalFreedom" : 50,
                    "theft" : 42,
                    "women" : 33
                  },
                  "self" : {
                    "methods" : [ "GET" ],
                    "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402734"
                  },
                  "subType" : "DISTRICT",
                  "type" : "safety-rated-location"
                }, {
                  "geoCode" : {
                    "latitude" : 41.4097037,
                    "longitude" : 2.1892366
                  },
                  "id" : "Q930402735",
                  "name" : "El Clot (Barcelona)",
                  "safetyScores" : {
                    "lgbtq" : 37,
                    "medical" : 0,
                    "overall" : 45,
                    "physicalHarm" : 35,
                    "politicalFreedom" : 50,
                    "theft" : 43,
                    "women" : 33
                  },
                  "self" : {
                    "methods" : [ "GET" ],
                    "type" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations/Q930402735"
                  },
                  "subType" : "DISTRICT",
                  "type" : "safety-rated-location"
                } ],
                "meta" : {
                  "count" : 43,
                  "links" : {
                    "first" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations?latitude=41.397158&longitude=2.160873&page%5Boffset%5D=0&radius=2",
                    "last" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations?latitude=41.397158&longitude=2.160873&page%5Boffset%5D=4&radius=2",
                    "next" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations?latitude=41.397158&longitude=2.160873&page%5Boffset%5D=1&radius=2",
                    "self" : "https://test.api.amadeus.com/v1/safety/safety-rated-locations?latitude=41.397158&longitude=2.160873&radius=2"
                  }
                }
              }
            }
          }
        }
      }
    },
    "parameters" : {
      "pageLimit" : {
        "name" : "page[limit]",
        "in" : "query",
        "description" : "maximum items in one page",
        "schema" : {
          "type" : "integer",
          "default" : 10
        }
      },
      "pageOffset" : {
        "name" : "page[offset]",
        "in" : "query",
        "description" : "start index of the requested page",
        "schema" : {
          "type" : "integer",
          "default" : 0
        }
      },
      "safety-rated-locationId" : {
        "name" : "safety-rated-locationId",
        "in" : "path",
        "description" : "identifier of the location",
        "required" : true,
        "schema" : {
          "type" : "string"
        },
        "example" : "Q930402719"
      }
    }
  }
}